package _2019330198_08;

import java.awt.Graphics;

public class Visual extends javax.swing.JFrame {
    public boolean grafica;
    private int nive_rec;
    private Dragon Drag;
    private Fractal Fract;
    private Hilbert Curva_h;
    private Sierpisnki trian;
    private Abelson Ab;
    private Koch Copo;
    private Gosper Go;
    private Mandelbrot Md;
    private Malmberg tejido;
    private Malmberg mazo;
    private Nest triangle;
    private Hooked snow;
    private AbelCornered Corn;
    
    public Visual() {
        initComponents();
        grafica = true;
        nive_rec = 3;
        this.setTitle("Bienvenido");
        Drag = new Dragon(lienzo,nive_rec,2);
        Curva_h = new Hilbert(lienzo,nive_rec,2);
        trian = new Sierpisnki(lienzo,nive_rec,3);
        Ab = new Abelson(lienzo, nive_rec, 2);
        Copo = new Koch(lienzo, nive_rec,30);
        Go = new Gosper(lienzo, nive_rec, 20);
        Md = new Mandelbrot(lienzo, nive_rec, 20);
        tejido = new Malmberg(lienzo, nive_rec,20,false);
        mazo = new Malmberg(lienzo, nive_rec, 20, true);
        triangle = new Nest(lienzo, nive_rec,20);
        snow = new Hooked(lienzo, nive_rec,20);
        Corn = new AbelCornered(lienzo,nive_rec,(nive_rec*48)%360,nive_rec,20);
        tejido.posicion(-10.0, 0.0);
        mazo.posicion(-10.0, 0.0);
        Drag.posicion(-10.0, 0.0);
        Corn.posicion(-10, 0);
        Curva_h.posicion(lienzo.getHeight()/2, lienzo.getWidth()/2);
        trian.posicion(lienzo.getHeight()/2, lienzo.getWidth()/2);
        Ab.posicion(lienzo.getHeight()/2, lienzo.getWidth()/2);
        Copo.posicion(lienzo.getHeight()/2,lienzo.getWidth()/2);
        Go.posicion(lienzo.getHeight()/2 , lienzo.getWidth()/2);
        Md.posicion(-10.0, 0);
        triangle.posicion(-10.0, 0.0);
        snow.posicion(-10,0);
        Fract = null;
        Spinner_rec.getModel().setValue(nive_rec);
        Spinner_rec.setEnabled(false);
        
    }
    
    public void paint(Graphics g){
        this.paintComponents(g);
        Graphics gr = this.lienzo.getGraphics();
      //  if(grafica)
        //    gr.drawLine(lienzo.getHeight()/2,lienzo.getWidth()/2, 100, 100);
        
        if(Fract != null && grafica){
            Fract.reinicia();
            Fract.setRecursion(nive_rec);
            //Fract.setAngulo((48*nive_rec)%360);
            Fract.setA(nive_rec*3);
            Fract.dibuja();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jButton1 = new javax.swing.JButton();
        lienzo = new javax.swing.JPanel();
        Spinner_rec = new javax.swing.JSpinner();
        Grafica = new javax.swing.JButton();
        No_Grafica = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        Grafica_Dragon = new javax.swing.JRadioButtonMenuItem();
        Curva_Hilbert = new javax.swing.JRadioButtonMenuItem();
        Sierpis = new javax.swing.JRadioButtonMenuItem();
        Abelson = new javax.swing.JRadioButtonMenuItem();
        Koch = new javax.swing.JRadioButtonMenuItem();
        Gosp = new javax.swing.JRadioButtonMenuItem();
        Mand = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        Weave = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        Hooked = new javax.swing.JRadioButtonMenuItem();
        Maze = new javax.swing.JRadioButtonMenuItem();

        jMenu1.setText("jMenu1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Spinner_rec.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Spinner_recStateChanged(evt);
            }
        });

        Grafica.setText("Grafica");
        Grafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraficaActionPerformed(evt);
            }
        });

        No_Grafica.setText("No Grafica");
        No_Grafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No_GraficaActionPerformed(evt);
            }
        });

        jMenu2.setText("Fractales Disponibles.");

        Grafica_Dragon.setSelected(true);
        Grafica_Dragon.setText("Dragon");
        Grafica_Dragon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grafica_DragonActionPerformed(evt);
            }
        });
        jMenu2.add(Grafica_Dragon);

        Curva_Hilbert.setSelected(true);
        Curva_Hilbert.setText("Curva de Hilbert");
        Curva_Hilbert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Curva_HilbertActionPerformed(evt);
            }
        });
        jMenu2.add(Curva_Hilbert);

        Sierpis.setSelected(true);
        Sierpis.setText("Sierpinski");
        Sierpis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SierpisActionPerformed(evt);
            }
        });
        jMenu2.add(Sierpis);

        Abelson.setSelected(true);
        Abelson.setText("Abelson");
        Abelson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbelsonActionPerformed(evt);
            }
        });
        jMenu2.add(Abelson);

        Koch.setSelected(true);
        Koch.setText("Koch Copo");
        Koch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KochActionPerformed(evt);
            }
        });
        jMenu2.add(Koch);

        Gosp.setSelected(true);
        Gosp.setText("Gosper");
        Gosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GospActionPerformed(evt);
            }
        });
        jMenu2.add(Gosp);

        Mand.setSelected(true);
        Mand.setText("Mandelbrot");
        Mand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MandActionPerformed(evt);
            }
        });
        jMenu2.add(Mand);

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("Cornered Polygons");
        jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem3);

        Weave.setSelected(true);
        Weave.setText("Weave");
        Weave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeaveActionPerformed(evt);
            }
        });
        jMenu2.add(Weave);

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Nested Triangles");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem2);

        Hooked.setSelected(true);
        Hooked.setText("Hooked Snowflake");
        Hooked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HookedActionPerformed(evt);
            }
        });
        jMenu2.add(Hooked);

        Maze.setSelected(true);
        Maze.setText("Maze");
        Maze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MazeActionPerformed(evt);
            }
        });
        jMenu2.add(Maze);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Spinner_rec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Grafica))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(No_Grafica)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Spinner_rec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(Grafica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                        .addComponent(No_Grafica)
                        .addGap(138, 138, 138))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Grafica_DragonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grafica_DragonActionPerformed
        // TODO add your handling code here:
        Drag.setEscala(3, 3);
        Fract = Drag;
        
        Spinner_rec.setEnabled(true);
    //    lienzo.getGraphics().drawLine(10, 10, 100, 100);
        repaint();
    }//GEN-LAST:event_Grafica_DragonActionPerformed

    private void Spinner_recStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Spinner_recStateChanged
        // TODO add your handling code here:
        nive_rec = (Integer)(Spinner_rec.getModel().getValue());
        if(nive_rec < 0 || nive_rec > 10){
            nive_rec = nive_rec < 0 ? 0 : 10;
            Spinner_rec.setValue(nive_rec);
        }
        repaint();
    }//GEN-LAST:event_Spinner_recStateChanged

    private void GraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraficaActionPerformed
        // TODO add your handling code here:
        grafica = true;
        repaint();
    }//GEN-LAST:event_GraficaActionPerformed

    private void No_GraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No_GraficaActionPerformed
        // TODO add your handling code here:
        grafica = false;
        repaint();
    }//GEN-LAST:event_No_GraficaActionPerformed

    private void Curva_HilbertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Curva_HilbertActionPerformed
        // TODO add your handling code here:
        Curva_h.setEscala(3, 3);
        Fract = Curva_h;
        Spinner_rec.setEnabled(true);
        repaint();
    }//GEN-LAST:event_Curva_HilbertActionPerformed

    private void SierpisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SierpisActionPerformed
        // TODO add your handling code here:
        trian.setEscala(5,5);
        Fract = trian;
        Spinner_rec.setEnabled(true);
        repaint();
    }//GEN-LAST:event_SierpisActionPerformed

    private void AbelsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbelsonActionPerformed
        // TODO add your handling code here:
        Ab.setEscala(2,2);
        Fract = Ab;
        Spinner_rec.setEnabled(true);
        repaint();
    }//GEN-LAST:event_AbelsonActionPerformed

    private void KochActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KochActionPerformed
        // TODO add your handling code here:
        Copo.setEscala(20,20);
        Fract = Copo;
        Spinner_rec.setEnabled(true);
        repaint();
    }//GEN-LAST:event_KochActionPerformed

    private void GospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GospActionPerformed
        // TODO add your handling code here:
        Go.setEscala(8,8);
        Fract = Go;
        Spinner_rec.setEnabled(true);
        repaint();
    }//GEN-LAST:event_GospActionPerformed

    private void MandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MandActionPerformed
        // TODO add your handling code here:
        Md.setEscala(15,15);
        Fract = Md;
        Spinner_rec.setEnabled(true);
        repaint();
    }//GEN-LAST:event_MandActionPerformed

    private void WeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeaveActionPerformed
        // TODO add your handling code here:
        tejido.SetEscala(20,20);
        Fract = tejido;
        Spinner_rec.setEnabled(true);
        repaint();
    }//GEN-LAST:event_WeaveActionPerformed

    private void MazeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MazeActionPerformed
        // TODO add your handling code here:
        mazo.SetEscala(20,20);
        Fract = mazo;
        Spinner_rec.setEnabled(true);
        repaint();
    }//GEN-LAST:event_MazeActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
        // TODO add your handling code here:
        triangle.setEscala(10,10);
        Fract = triangle;
        Spinner_rec.setEnabled(true);
        repaint();
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void HookedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HookedActionPerformed
        // TODO add your handling code here:
        snow.setEscala(18,18);
        Fract = snow;
        Spinner_rec.setEnabled(true);
        repaint();
    }//GEN-LAST:event_HookedActionPerformed

    private void jRadioButtonMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem3ActionPerformed
        // TODO add your handling code here:
        Corn.setEscala(5,5);
        Fract = Corn;
        Spinner_rec.setEnabled(true);
        repaint();
    }//GEN-LAST:event_jRadioButtonMenuItem3ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem Abelson;
    private javax.swing.JRadioButtonMenuItem Curva_Hilbert;
    private javax.swing.JRadioButtonMenuItem Gosp;
    private javax.swing.JButton Grafica;
    private javax.swing.JRadioButtonMenuItem Grafica_Dragon;
    private javax.swing.JRadioButtonMenuItem Hooked;
    private javax.swing.JRadioButtonMenuItem Koch;
    private javax.swing.JRadioButtonMenuItem Mand;
    private javax.swing.JRadioButtonMenuItem Maze;
    private javax.swing.JButton No_Grafica;
    private javax.swing.JRadioButtonMenuItem Sierpis;
    private javax.swing.JSpinner Spinner_rec;
    private javax.swing.JRadioButtonMenuItem Weave;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JPanel lienzo;
    // End of variables declaration//GEN-END:variables
}
